version: "3.8"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  celery_worker:
    build: .
    command: celery -A discord_logview worker -l warning
    depends_on:
      - redis
      - web
  celery_beat:
    build: .
    command: celery -A discord_logview beat --max-interval 3600
    depends_on:
      - celery_worker
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  redis:
    image: redis:4.0.9
    expose:
      - 6379

volumes:
  postgres_data: