version: "3"
services:
  database:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecure

  redis:
    image: redis:5-alpine
    command: redis-server --requirepass secureredis
    ports:
      - '6379:6379'

  logs:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    restart: 'no'
    container_name: logs
    volumes:
      - .:/srv/
    depends_on:
      - database
      - redis
    ports:
      - "80:80"
    env_file:
      - ./docker-compose.env
